registration_category = {
    ("RA", "Investment Advisor Representative")
}

registration_status = {
    ("ABANDONED", "Abandoned"),
    ("ADMTERM", "Administrative Termination"),
    ("APPRNT", "Approved Pending Prints"),
    ("APPROVED", "Approved"),
    ("APPROVED_RES", "Restricted Approval"),
    ("APRSLTS", "Approved Pending Results"),
    ("BAR", "Bar"),
    ("CE2_YEAR_TRMD", "Termed CE Two Year Inactive"),
    ("CE_INACTIVE", "Inactive - Continuing Education"),
    ("DEFICIENT", "Deficient"),
    ("DENIED", "Denied"),
    ("FTR", "Terminated Failure to Renew"),
    ("INACTIVE_PRINTS", "Inactive - Prints"),
    ("MASS_TRNSF", "Termed Mass Transfer"),
    ("PENDING", "Pending"),
    ("PURGED", "Purged"),
    ("REJECTED", "Rejected"),
    ("REQUAL", "Requalification"),
    ("REQUEST_TERM", "Termination Requested"),
    ("REVOKED", "Revoked"),
    ("SUSPENSION", "Suspended"),
    ("TEMPREG", "Temporary Registration"),
    ("TERMED", "Termed"),
    ("T_NOREG", "Termed Without Registration"),
    ("T_NOREG_FTR", "Terminated no registration Renewals"),
    ("T_NOREG_MT", "Terminated no registration Mass Transfer"),
    ("T_NOU5", "Terminated Without U5"),
    ("TEMP_WD", "Temporary Withdrawal"),
    ("T_NOMT", "Termed-Did Not Mass Transfer"),
    ("T_NOMTNOREG", "Terminated no reg.-Did Not Mass Transfer"),
    ("TRANS_RQST", "Transition Requested"),
    ("TRANS_TERM", "Transition Terminated"),
    ("TRANS_ERROR", "Not Transitioned - Filed In Error")
}

state_code = {
    ("AK", "Alaska"),
    ("AL", "Alabama"),
    ("AR", "Arkansas"),
    ("AZ", "Arizona"),
    ("CA", "California"),
    ("CO", "Colorado"),
    ("CT", "Connecticut"),
    ("DC", "District of Columbia"),
    ("DE", "Delaware"),
    ("FL", "Florida"),
    ("GA", "Georgia"),
    ("GU", "Guam"),
    ("HI", "Hawaii"),
    ("IA", "Iowa"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IN", "Indiana"),
    ("KS", "Kansas"),
    ("KY", "Kentucky"),
    ("LA", "Louisiana"),
    ("MA", "Massachusetts"),
    ("MD", "Maryland"),
    ("ME", "Maine"),
    ("MI", "Michigan"),
    ("MN", "Minnesota"),
    ("MO", "Missouri"),
    ("MS", "Mississippi"),
    ("MT", "Montana"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("NE", "Nebraska"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NV", "Nevada"),
    ("NY", "New York"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OR", "Oregon"),
    ("PA", "Pennsylvania"),
    ("PR", "Puerto Rico"),
    ("RI", "Rhode Island"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("TN", "Tennessee"),
    ("TX", "Texas"),
    ("UT", "Utah"),
    ("VA", "Virginia"),
    ("VT", "Vermont"),
    ("WA", "Washington"),
    ("WI", "Wisconsin"),
    ("WV", "West Virginia"),
    ("WY", "Wyoming"),
    ("VI", "Virgin Islands")
}

exam_code = {
    ("S63", "Uniform Securities Agent State Law Examination"),
    ("S64", "NASAA Real Estate Securities Exam"),
    ("S65", "Uniform Investment Adviser Law Examination"),
    ("S66", "Uniform Combined State Law Examination")
}